### ISSUE TITLE
release on pypi

### ISSUE THREAD

**Issue by flokain** [open-networks/certbot-bigip#3]
**Is your feature request related to a problem? Please describe.**
autmatically release on pypi when test pass at on

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
snippet from old pipline

```yaml
compile package:
  <<: *base_job
  stage: build
  script:
    - python setup.py sdist
  only:
    - tags
  except:
    - branches
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - dist/
    expire_in: 10 mins

release on pypi:
  <<: *base_job
  image: python:3
  stage: release
  script:
    - pip install -U twine
    - twine upload dist/*
  only:
    - tags
  except:
    - branches
```
